### ISSUE TITLE
.psd file are to large

### ISSUE THREAD

**Issue by DonFlymoor** [GabrieleGiuseppini/Floating-Sandbox#46]
The .psd files are to large for me to download over my limited bandwidth. Earlier, you had replaced them with git LFS, and that worked well. Why did you decide to put them back?

**Comment by GabrieleGiuseppini** [comment]
Hi, I had to disable LFS again because its monthly bandwidth has a limit, and each person cloning the repo would remove from that limit, locking the LFS storage for the whole month. With the latest git's it's possible to only clone/pull specific folder, see if https://stackoverflow.com/questions/600079/git-how-do-i-clone-a-subdirectory-only-of-a-git-repository or https://askubuntu.com/questions/460885/how-to-clone-only-some-directories-from-a-git-repository/729798#729798 work for you.
